/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package timebnf;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void _12_01() {
        App classUnderTest = new App();
        assertEquals(classUnderTest.getMinutesAfterMidnight("12:01"),1);
    }
}
