/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package timebnf;

import org.antlr.runtime.CharStream;
import org.antlr.v4.runtime.CharStreams;
import org.antlr.v4.runtime.CodePointCharStream;
import org.antlr.v4.runtime.CommonTokenStream;
import org.antlr.v4.runtime.TokenStream;

public class App {


    public static void main(String[] args) {

    }

    public int getMinutesAfterMidnight(String time){
        CodePointCharStream inputStream = CharStreams.fromString(time);
        TimeLexer lexer = new TimeLexer(inputStream);
        TokenStream tokens = new CommonTokenStream(lexer);
        TimeParser parser = new TimeParser(tokens);
        TimeParser.TimeContext timeContext = parser.time();

        return -1;
    }
}
